"public"	"analises"	"id"	"integer"
"public"	"analises"	"capitulo_id"	"integer"
"public"	"analises"	"critica"	"text"
"public"	"analises"	"aplicacao_pratica"	"text"
"public"	"analises"	"conexoes"	"text"
"public"	"analises"	"comentarios_extra"	"text"
"public"	"analises"	"lancamento_aviso"	"text"
"public"	"analises"	"lancamento_ativo"	"boolean"
"public"	"analises"	"imagem_ai_1"	"text"
"public"	"analises"	"imagem_ai_2"	"text"
"public"	"analises"	"imagem_ai_3"	"text"
"public"	"assinatura"	"id"	"integer"
"public"	"assinatura"	"tipo"	"character varying"
"public"	"assinatura"	"preco"	"double precision"
"public"	"assinatura"	"duracao"	"integer"
"public"	"assinatura"	"recursos_inclusos"	"character varying"
"public"	"assinatura"	"provider_price_id"	"text"
"public"	"badges"	"id"	"integer"
"public"	"badges"	"code"	"character varying"
"public"	"badges"	"nome"	"character varying"
"public"	"badges"	"descricao"	"text"
"public"	"badges"	"xp_threshold"	"integer"
"public"	"badges"	"auto_award"	"boolean"
"public"	"badges"	"created_at"	"timestamp with time zone"
"public"	"blog_posts"	"id"	"integer"
"public"	"blog_posts"	"title"	"character varying"
"public"	"blog_posts"	"slug"	"character varying"
"public"	"blog_posts"	"summary"	"character varying"
"public"	"blog_posts"	"content"	"text"
"public"	"blog_posts"	"is_published"	"boolean"
"public"	"blog_posts"	"created_at"	"timestamp with time zone"
"public"	"blog_posts"	"updated_at"	"timestamp with time zone"
"public"	"capitulo_examples"	"id"	"bigint"
"public"	"capitulo_examples"	"capitulo_id"	"integer"
"public"	"capitulo_examples"	"kind"	"character varying"
"public"	"capitulo_examples"	"titulo"	"text"
"public"	"capitulo_examples"	"texto"	"text"
"public"	"capitulo_examples"	"tags"	"text"
"public"	"capitulo_examples"	"fonte"	"text"
"public"	"capitulo_examples"	"created_at"	"timestamp with time zone"
"public"	"capitulo_keyword_images"	"id"	"integer"
"public"	"capitulo_keyword_images"	"capitulo_id"	"integer"
"public"	"capitulo_keyword_images"	"keyword"	"text"
"public"	"capitulo_keyword_images"	"image_url"	"text"
"public"	"capitulo_keyword_images"	"created_at"	"timestamp with time zone"
"public"	"capitulos"	"id"	"integer"
"public"	"capitulos"	"titulo"	"character varying"
"public"	"capitulos"	"numero"	"integer"
"public"	"capitulos"	"conteudo"	"text"
"public"	"capitulos"	"livro_id"	"integer"
"public"	"capitulos"	"pre_lancamento_aviso"	"text"
"public"	"capitulos"	"pre_lancamento_ativo"	"boolean"
"public"	"capitulos"	"imagem_ai_1"	"text"
"public"	"capitulos"	"imagem_ai_2"	"text"
"public"	"capitulos"	"imagem_ai_3"	"text"
"public"	"capitulos"	"slug"	"character varying"
"public"	"capitulos"	"views"	"integer"
"public"	"categorias"	"id"	"integer"
"public"	"categorias"	"subcategoria"	"character varying"
"public"	"categorias"	"nome"	"character varying"
"public"	"categorias"	"descricao"	"character varying"
"public"	"categorias"	"slug"	"character varying"
"public"	"challenges"	"id"	"integer"
"public"	"challenges"	"checkpoint_id"	"integer"
"public"	"challenges"	"tipo"	"character varying"
"public"	"challenges"	"titulo"	"character varying"
"public"	"challenges"	"descricao"	"text"
"public"	"challenges"	"rubric_id"	"integer"
"public"	"challenges"	"xp_reward"	"integer"
"public"	"challenges"	"max_score"	"integer"
"public"	"challenges"	"created_at"	"timestamp with time zone"
"public"	"chapter_images"	"id"	"bigint"
"public"	"chapter_images"	"capitulo_id"	"integer"
"public"	"chapter_images"	"url"	"text"
"public"	"chapter_images"	"alt_text"	"text"
"public"	"chapter_images"	"kind"	"character varying"
"public"	"chapter_images"	"created_at"	"timestamp with time zone"
"public"	"checkpoints"	"id"	"integer"
"public"	"checkpoints"	"titulo"	"character varying"
"public"	"checkpoints"	"descricao"	"text"
"public"	"checkpoints"	"learning_path_item_id"	"integer"
"public"	"checkpoints"	"livro_id"	"integer"
"public"	"checkpoints"	"capitulo_id"	"integer"
"public"	"checkpoints"	"ordem"	"integer"
"public"	"checkpoints"	"xp_reward"	"integer"
"public"	"checkpoints"	"required"	"boolean"
"public"	"checkpoints"	"rubric_id"	"integer"
"public"	"checkpoints"	"created_at"	"timestamp with time zone"
"public"	"empresas"	"emp_id"	"integer"
"public"	"empresas"	"emp_nome"	"character varying"
"public"	"empresas"	"emp_cnpj"	"character varying"
"public"	"empresas"	"emp_endereco"	"character varying"
"public"	"empresas"	"emp_tipo_plataforma"	"character varying"
"public"	"events"	"id"	"integer"
"public"	"events"	"usuario_id"	"integer"
"public"	"events"	"type"	"character varying"
"public"	"events"	"payload"	"text"
"public"	"events"	"created_at"	"timestamp without time zone"
"public"	"faqs"	"id"	"integer"
"public"	"faqs"	"pergunta"	"character varying"
"public"	"faqs"	"resposta"	"text"
"public"	"faqs"	"author_user_id"	"integer"
"public"	"faqs"	"is_published"	"boolean"
"public"	"faqs"	"created_at"	"timestamp with time zone"
"public"	"faqs"	"updated_at"	"timestamp with time zone"
"public"	"favorites_folder"	"id"	"bigint"
"public"	"favorites_folder"	"owner_id"	"bigint"
"public"	"favorites_folder"	"name"	"text"
"public"	"favorites_folder"	"description"	"text"
"public"	"favorites_folder"	"is_public"	"boolean"
"public"	"favorites_folder"	"created_at"	"timestamp with time zone"
"public"	"favorites_folder"	"updated_at"	"timestamp with time zone"
"public"	"favorites_folder_share"	"id"	"bigint"
"public"	"favorites_folder_share"	"folder_id"	"bigint"
"public"	"favorites_folder_share"	"user_id"	"bigint"
"public"	"favorites_folder_share"	"role"	"USER-DEFINED"
"public"	"favorites_folder_share"	"created_at"	"timestamp with time zone"
"public"	"favorites_item"	"id"	"bigint"
"public"	"favorites_item"	"folder_id"	"bigint"
"public"	"favorites_item"	"item_type"	"USER-DEFINED"
"public"	"favorites_item"	"item_id"	"bigint"
"public"	"favorites_item"	"added_by"	"bigint"
"public"	"favorites_item"	"note"	"text"
"public"	"favorites_item"	"created_at"	"timestamp with time zone"
"public"	"favoritos"	"id"	"integer"
"public"	"favoritos"	"usuario_id"	"integer"
"public"	"favoritos"	"livro_id"	"integer"
"public"	"favoritos"	"capitulo_id"	"integer"
"public"	"favoritos"	"data_adicionado"	"timestamp without time zone"
"public"	"features"	"id"	"integer"
"public"	"features"	"code"	"text"
"public"	"features"	"name"	"text"
"public"	"features"	"description"	"text"
"public"	"features"	"category"	"text"
"public"	"features"	"created_at"	"timestamp with time zone"
"public"	"learning_path_items"	"id"	"integer"
"public"	"learning_path_items"	"caminho_id"	"integer"
"public"	"learning_path_items"	"tipo_conteudo"	"text"
"public"	"learning_path_items"	"conteudo_id"	"integer"
"public"	"learning_path_items"	"posicao"	"integer"
"public"	"learning_path_items"	"criado_em"	"timestamp with time zone"
"public"	"learning_paths"	"id"	"integer"
"public"	"learning_paths"	"titulo"	"text"
"public"	"learning_paths"	"descricao"	"text"
"public"	"learning_paths"	"criado_em"	"timestamp with time zone"
"public"	"learning_paths"	"slug"	"character varying"
"public"	"learning_paths"	"categoria_id"	"integer"
"public"	"livros"	"id"	"integer"
"public"	"livros"	"titulo"	"character varying"
"public"	"livros"	"autor"	"character varying"
"public"	"livros"	"isbn"	"character varying"
"public"	"livros"	"editora"	"character varying"
"public"	"livros"	"genero"	"character varying"
"public"	"livros"	"ano_publicacao"	"integer"
"public"	"livros"	"categoria_id"	"integer"
"public"	"livros"	"pre_lancamento_aviso"	"text"
"public"	"livros"	"pre_lancamento_ativo"	"boolean"
"public"	"livros"	"imagem_ai_1"	"text"
"public"	"livros"	"imagem_ai_2"	"text"
"public"	"livros"	"imagem_ai_3"	"text"
"public"	"livros"	"premium_only"	"boolean"
"public"	"livros"	"slug"	"character varying"
"public"	"livros"	"views"	"integer"
"public"	"livros_categorias"	"livro_id"	"integer"
"public"	"livros_categorias"	"categoria_id"	"integer"
"public"	"minigame_custom_questions"	"id"	"integer"
"public"	"minigame_custom_questions"	"tema_id"	"integer"
"public"	"minigame_custom_questions"	"tema_nome"	"character varying"
"public"	"minigame_custom_questions"	"texto"	"text"
"public"	"minigame_custom_questions"	"correta"	"character varying"
"public"	"minigame_custom_questions"	"incorreta1"	"character varying"
"public"	"minigame_custom_questions"	"incorreta2"	"character varying"
"public"	"minigame_custom_questions"	"incorreta3"	"character varying"
"public"	"minigame_custom_questions"	"created_by_user_id"	"integer"
"public"	"minigame_custom_questions"	"ativo"	"boolean"
"public"	"minigame_custom_questions"	"created_at"	"timestamp without time zone"
"public"	"minigame_custom_themes"	"id"	"integer"
"public"	"minigame_custom_themes"	"nome"	"character varying"
"public"	"minigame_custom_themes"	"created_by_user_id"	"integer"
"public"	"minigame_custom_themes"	"ativo"	"boolean"
"public"	"minigame_custom_themes"	"created_at"	"timestamp without time zone"
"public"	"minigame_definitions"	"id"	"integer"
"public"	"minigame_definitions"	"slug"	"character varying"
"public"	"minigame_definitions"	"titulo"	"character varying"
"public"	"minigame_definitions"	"descricao"	"text"
"public"	"minigame_definitions"	"tema"	"character varying"
"public"	"minigame_definitions"	"dificuldade"	"character varying"
"public"	"minigame_definitions"	"xp_reward"	"integer"
"public"	"minigame_definitions"	"checkpoint_id"	"integer"
"public"	"minigame_definitions"	"challenge_id"	"integer"
"public"	"minigame_definitions"	"ativo"	"boolean"
"public"	"minigame_definitions"	"created_at"	"timestamp with time zone"
"public"	"news_items"	"id"	"integer"
"public"	"news_items"	"title"	"character varying"
"public"	"news_items"	"summary"	"character varying"
"public"	"news_items"	"body"	"text"
"public"	"news_items"	"version"	"character varying"
"public"	"news_items"	"is_published"	"boolean"
"public"	"news_items"	"created_at"	"timestamp with time zone"
"public"	"news_seen"	"id"	"integer"
"public"	"news_seen"	"user_id"	"integer"
"public"	"news_seen"	"news_id"	"integer"
"public"	"news_seen"	"seen_at"	"timestamp with time zone"
"public"	"password_reset_tokens"	"id"	"integer"
"public"	"password_reset_tokens"	"user_id"	"integer"
"public"	"password_reset_tokens"	"token"	"character varying"
"public"	"password_reset_tokens"	"used"	"boolean"
"public"	"password_reset_tokens"	"created_at"	"timestamp without time zone"
"public"	"password_reset_tokens"	"expires_at"	"timestamp without time zone"
"public"	"pesquisas"	"id"	"integer"
"public"	"pesquisas"	"termo_buscado"	"character varying"
"public"	"pesquisas"	"data_hora"	"timestamp without time zone"
"public"	"pesquisas"	"usuario_id"	"integer"
"public"	"plan_features"	"assinatura_id"	"integer"
"public"	"plan_features"	"feature_id"	"integer"
"public"	"plan_features"	"created_at"	"timestamp with time zone"
"public"	"plan_settings"	"id"	"integer"
"public"	"plan_settings"	"assinatura_id"	"integer"
"public"	"plan_settings"	"key"	"character varying"
"public"	"plan_settings"	"value"	"character varying"
"public"	"resumo_audio"	"id"	"integer"
"public"	"resumo_audio"	"resumo_id"	"integer"
"public"	"resumo_audio"	"audio_url"	"text"
"public"	"resumo_audio"	"voice"	"text"
"public"	"resumo_audio"	"speed"	"double precision"
"public"	"resumo_audio"	"duration_seconds"	"integer"
"public"	"resumo_audio"	"offline_available"	"boolean"
"public"	"resumo_audio"	"created_at"	"timestamp with time zone"
"public"	"resumos"	"id"	"integer"
"public"	"resumos"	"texto_resumo"	"text"
"public"	"resumos"	"data_criacao"	"timestamp without time zone"
"public"	"resumos"	"gerado_por_ia"	"boolean"
"public"	"resumos"	"usuario_id"	"integer"
"public"	"resumos"	"capitulo_id"	"integer"
"public"	"resumos"	"tipo"	"character varying"
"public"	"resumos"	"livro_id"	"integer"
"public"	"rubrics"	"id"	"integer"
"public"	"rubrics"	"nome"	"character varying"
"public"	"rubrics"	"descricao"	"text"
"public"	"rubrics"	"criterios_json"	"text"
"public"	"rubrics"	"total_peso"	"double precision"
"public"	"rubrics"	"created_at"	"timestamp with time zone"
"public"	"simulado_questoes"	"id"	"integer"
"public"	"simulado_questoes"	"simulado_id"	"integer"
"public"	"simulado_questoes"	"enunciado"	"text"
"public"	"simulado_questoes"	"alternativas"	"jsonb"
"public"	"simulado_questoes"	"resposta_correta"	"integer"
"public"	"simulado_questoes"	"referencias"	"jsonb"
"public"	"simulado_resultados"	"id"	"integer"
"public"	"simulado_resultados"	"simulado_id"	"integer"
"public"	"simulado_resultados"	"usuario_id"	"integer"
"public"	"simulado_resultados"	"acertos"	"integer"
"public"	"simulado_resultados"	"total"	"integer"
"public"	"simulado_resultados"	"respostas"	"jsonb"
"public"	"simulado_resultados"	"criado_em"	"timestamp with time zone"
"public"	"simulado_shares"	"id"	"integer"
"public"	"simulado_shares"	"simulado_id"	"integer"
"public"	"simulado_shares"	"from_usuario_id"	"integer"
"public"	"simulado_shares"	"to_email"	"text"
"public"	"simulado_shares"	"mensagem"	"text"
"public"	"simulado_shares"	"criado_em"	"timestamp without time zone"
"public"	"simulados"	"id"	"integer"
"public"	"simulados"	"usuario_id"	"integer"
"public"	"simulados"	"livro_id"	"integer"
"public"	"simulados"	"capitulo_id"	"integer"
"public"	"simulados"	"pontuacao"	"integer"
"public"	"simulados"	"data_execucao"	"timestamp without time zone"
"public"	"simulados"	"pesquisa_id"	"integer"
"public"	"simulados"	"quantidade"	"integer"
"public"	"simulados"	"criado_em"	"timestamp with time zone"
"public"	"subuser_categorias"	"id"	"integer"
"public"	"subuser_categorias"	"subuser_link_id"	"integer"
"public"	"subuser_categorias"	"categoria_id"	"integer"
"public"	"subuser_links"	"id"	"integer"
"public"	"subuser_links"	"owner_id"	"integer"
"public"	"subuser_links"	"subuser_id"	"integer"
"public"	"subuser_links"	"allowed_levels"	"character varying"
"public"	"subuser_links"	"created_at"	"timestamp without time zone"
"public"	"subuser_links"	"email"	"character varying"
"public"	"subuser_links"	"status"	"USER-DEFINED"
"public"	"subuser_links"	"token"	"character varying"
"public"	"subuser_links"	"token_expiry"	"timestamp with time zone"
"public"	"subuser_links"	"accepted_at"	"timestamp with time zone"
"public"	"subuser_links"	"allowed_features"	"character varying"
"public"	"subuser_topicos"	"id"	"integer"
"public"	"subuser_topicos"	"subuser_link_id"	"integer"
"public"	"subuser_topicos"	"topico_id"	"integer"
"public"	"subuser_trilhas"	"id"	"integer"
"public"	"subuser_trilhas"	"subuser_link_id"	"integer"
"public"	"subuser_trilhas"	"learning_path_id"	"integer"
"public"	"classrooms"	"id"	"integer"
"public"	"classrooms"	"owner_usuario_id"	"integer"
"public"	"classrooms"	"nome"	"character varying"
"public"	"classrooms"	"descricao"	"character varying"
"public"	"classrooms"	"created_at"	"timestamp with time zone"
"public"	"subuser_classrooms"	"id"	"integer"
"public"	"subuser_classrooms"	"subuser_link_id"	"integer"
"public"	"subuser_classrooms"	"classroom_id"	"integer"
"public"	"subuser_shares"	"id"	"integer"
"public"	"subuser_shares"	"subuser_link_id"	"integer"
"public"	"subuser_shares"	"from_owner_id"	"integer"
"public"	"subuser_shares"	"to_owner_id"	"integer"
"public"	"subuser_shares"	"created_at"	"timestamp with time zone"
"public"	"subuser_simulados"	"id"	"integer"
"public"	"subuser_simulados"	"subuser_link_id"	"integer"
"public"	"subuser_simulados"	"simulado_id"	"integer"
"public"	"subuser_livros"	"id"	"integer"
"public"	"subuser_livros"	"subuser_link_id"	"integer"
"public"	"subuser_livros"	"livro_id"	"integer"
"public"	"subuser_minigame_themes"	"id"	"integer"
"public"	"subuser_minigame_themes"	"subuser_link_id"	"integer"
"public"	"subuser_minigame_themes"	"tema_id"	"integer"
"public"	"support_messages"	"id"	"integer"
"public"	"support_messages"	"thread_id"	"integer"
"public"	"support_messages"	"sender_user_id"	"integer"
"public"	"support_messages"	"sender_is_admin"	"boolean"
"public"	"support_messages"	"content"	"text"
"public"	"support_messages"	"created_at"	"timestamp with time zone"
"public"	"support_threads"	"id"	"integer"
"public"	"support_threads"	"user_id"	"integer"
"public"	"support_threads"	"title"	"character varying"
"public"	"support_threads"	"status"	"character varying"
"public"	"support_threads"	"created_at"	"timestamp with time zone"
"public"	"task_submissions"	"id"	"integer"
"public"	"task_submissions"	"challenge_id"	"integer"
"public"	"task_submissions"	"usuario_id"	"integer"
"public"	"task_submissions"	"submitted_at"	"timestamp with time zone"
"public"	"task_submissions"	"answers_json"	"text"
"public"	"task_submissions"	"self_scores_json"	"text"
"public"	"task_submissions"	"evaluator_scores_json"	"text"
"public"	"task_submissions"	"status"	"character varying"
"public"	"task_submissions"	"final_score"	"double precision"
"public"	"topico_capitulos"	"topico_id"	"integer"
"public"	"topico_capitulos"	"capitulo_id"	"integer"
"public"	"topico_compilados"	"id"	"integer"
"public"	"topico_compilados"	"topico_id"	"integer"
"public"	"topico_compilados"	"versao"	"integer"
"public"	"topico_compilados"	"titulo"	"character varying"
"public"	"topico_compilados"	"slug"	"character varying"
"public"	"topico_compilados"	"texto_unificado"	"text"
"public"	"topico_compilados"	"origem"	"character varying"
"public"	"topico_compilados"	"modelo_ia"	"character varying"
"public"	"topico_compilados"	"prompt_base"	"text"
"public"	"topico_compilados"	"livro_count"	"integer"
"public"	"topico_compilados"	"created_at"	"timestamp with time zone"
"public"	"topico_compilados"	"updated_at"	"timestamp with time zone"
"public"	"topico_resumos"	"topico_id"	"integer"
"public"	"topico_resumos"	"resumo_id"	"integer"
"public"	"topicos"	"top_id"	"integer"
"public"	"topicos"	"titulo"	"character varying"
"public"	"topicos"	"descricao"	"text"
"public"	"topicos"	"criado_por_ia"	"boolean"
"public"	"topicos"	"data_criacao"	"timestamp without time zone"
"public"	"topicos"	"slug"	"character varying"
"public"	"transacoes"	"id"	"integer"
"public"	"transacoes"	"usuario_id"	"integer"
"public"	"transacoes"	"assinatura_id"	"integer"
"public"	"transacoes"	"valor"	"numeric"
"public"	"transacoes"	"status"	"character varying"
"public"	"transacoes"	"metodo_pagamento"	"character varying"
"public"	"transacoes"	"referencia_api"	"character varying"
"public"	"transacoes"	"data_criacao"	"timestamp without time zone"
"public"	"transacoes"	"forma_pagamento"	"character varying"
"public"	"transacoes"	"recorrencia"	"character varying"
"public"	"transacoes"	"webhook_event_id"	"text"
"public"	"user_badges"	"id"	"integer"
"public"	"user_badges"	"usuario_id"	"integer"
"public"	"user_badges"	"badge_id"	"integer"
"public"	"user_badges"	"awarded_at"	"timestamp with time zone"
"public"	"user_learning_paths"	"id"	"integer"
"public"	"user_learning_paths"	"caminho_id"	"integer"
"public"	"user_learning_paths"	"usuario_id"	"integer"
"public"	"user_learning_paths"	"atribuido_em"	"timestamp with time zone"
"public"	"user_progress"	"id"	"integer"
"public"	"user_progress"	"usuario_id"	"integer"
"public"	"user_progress"	"checkpoint_id"	"integer"
"public"	"user_progress"	"completed_at"	"timestamp with time zone"
"public"	"user_progress"	"progress_pct"	"double precision"
"public"	"user_progress"	"updated_at"	"timestamp with time zone"
"public"	"user_xp"	"id"	"integer"
"public"	"user_xp"	"usuario_id"	"integer"
"public"	"user_xp"	"xp_total"	"integer"
"public"	"user_xp"	"updated_at"	"timestamp with time zone"
"public"	"usuario_meta"	"id"	"integer"
"public"	"usuario_meta"	"usuario_id"	"integer"
"public"	"usuario_meta"	"goal"	"text"
"public"	"usuario_meta"	"created_at"	"timestamp with time zone"
"public"	"usuario_preferences"	"id"	"integer"
"public"	"usuario_preferences"	"usuario_id"	"integer"
"public"	"usuario_preferences"	"nivel"	"character varying"
"public"	"usuario_preferences"	"disponibilidade_semana"	"integer"
"public"	"usuario_preferences"	"prefere_audio"	"boolean"
"public"	"usuario_preferences"	"prefere_simulado"	"boolean"
"public"	"usuario_preferences"	"interesses"	"text"
"public"	"usuarios"	"id"	"integer"
"public"	"usuarios"	"nome"	"character varying"
"public"	"usuarios"	"email"	"character varying"
"public"	"usuarios"	"senha"	"character varying"
"public"	"usuarios"	"data_registro"	"timestamp without time zone"
"public"	"usuarios"	"status_assinatura"	"character varying"
"public"	"usuarios"	"assinatura_id"	"integer"
"public"	"usuarios"	"assinatura_expira_em"	"timestamp with time zone"
"public"	"usuarios"	"provider_customer_id"	"text"
"public"	"usuarios"	"provider_subscription_id"	"text"
"public"	"usuarios"	"username"	"character varying"
"public"	"webhook_events"	"id"	"integer"
"public"	"webhook_events"	"provider"	"character varying"
"public"	"webhook_events"	"event_id"	"character varying"
"public"	"webhook_events"	"event_type"	"character varying"
"public"	"webhook_events"	"payload"	"jsonb"
"public"	"webhook_events"	"received_at"	"timestamp with time zone"
"public"	"webhook_events"	"signature_valid"	"boolean"
"public"	"webhook_events"	"processed"	"boolean"
"public"	"webhook_events"	"transacao_id"	"integer"

"public"	"artifact_versions"	"id"	"integer"
"public"	"artifact_versions"	"entity_type"	"character varying"
"public"	"artifact_versions"	"entity_id"	"integer"
"public"	"artifact_versions"	"usuario_id"	"integer"
"public"	"artifact_versions"	"snapshot_json"	"text"
"public"	"artifact_versions"	"created_at"	"timestamp with time zone"
"public"	"artifact_versions"	"change_note"	"text"

"public"	"topico_compilado_livros"	"id"	"integer"
"public"	"topico_compilado_livros"	"topico_compilado_id"	"integer"
"public"	"topico_compilado_livros"	"livro_id"	"integer"
"public"	"topico_compilado_livros"	"posicao"	"integer"




contraint: 
"usuarios_assinatura_id_fkey"	"usuarios"	"assinatura_id"	"assinatura"	"id"
"capitulos_livro_id_fkey"	"capitulos"	"livro_id"	"livros"	"id"
"livros_categorias_categoria_id_fkey"	"livros_categorias"	"categoria_id"	"categorias"	"id"
"livros_categorias_livro_id_fkey"	"livros_categorias"	"livro_id"	"livros"	"id"
"fk_resumos_livro_id"	"resumos"	"livro_id"	"livros"	"id"
"resumos_capitulo_id_fkey"	"resumos"	"capitulo_id"	"capitulos"	"id"
"resumos_livro_id_fkey"	"resumos"	"livro_id"	"livros"	"id"
"resumos_usuario_id_fkey"	"resumos"	"usuario_id"	"usuarios"	"id"
"pesquisas_usuario_id_fkey"	"pesquisas"	"usuario_id"	"usuarios"	"id"
"favoritos_capitulo_id_fkey"	"favoritos"	"capitulo_id"	"capitulos"	"id"
"favoritos_livro_id_fkey"	"favoritos"	"livro_id"	"livros"	"id"
"favoritos_usuario_id_fkey"	"favoritos"	"usuario_id"	"usuarios"	"id"
"fk_simulado_capitulo"	"simulados"	"capitulo_id"	"capitulos"	"id"
"fk_simulado_livro"	"simulados"	"livro_id"	"livros"	"id"
"fk_simulado_pesquisa"	"simulados"	"pesquisa_id"	"pesquisas"	"id"
"fk_simulado_usuario"	"simulados"	"usuario_id"	"usuarios"	"id"
"simulados_capitulo_id_fkey"	"simulados"	"capitulo_id"	"capitulos"	"id"
"simulados_livro_id_fkey"	"simulados"	"livro_id"	"livros"	"id"
"simulados_usuario_id_fkey"	"simulados"	"usuario_id"	"usuarios"	"id"
"analises_capitulo_id_fkey"	"analises"	"capitulo_id"	"capitulos"	"id"
"favorites_folder_owner_id_fkey"	"favorites_folder"	"owner_id"	"usuarios"	"id"
"favorites_item_added_by_fkey"	"favorites_item"	"added_by"	"usuarios"	"id"
"favorites_item_folder_id_fkey"	"favorites_item"	"folder_id"	"favorites_folder"	"id"
"favorites_folder_share_folder_id_fkey"	"favorites_folder_share"	"folder_id"	"favorites_folder"	"id"
"favorites_folder_share_user_id_fkey"	"favorites_folder_share"	"user_id"	"usuarios"	"id"
"simulado_questoes_simulado_id_fkey"	"simulado_questoes"	"simulado_id"	"simulados"	"id"
"simulado_resultados_simulado_id_fkey"	"simulado_resultados"	"simulado_id"	"simulados"	"id"
"simulado_resultados_usuario_id_fkey"	"simulado_resultados"	"usuario_id"	"usuarios"	"id"
"simulado_shares_from_usuario_id_fkey"	"simulado_shares"	"from_usuario_id"	"usuarios"	"id"
"simulado_shares_simulado_id_fkey"	"simulado_shares"	"simulado_id"	"simulados"	"id"
"password_reset_tokens_user_id_fkey"	"password_reset_tokens"	"user_id"	"usuarios"	"id"
"transacoes_assinatura_id_fkey"	"transacoes"	"assinatura_id"	"assinatura"	"id"
"transacoes_usuario_id_fkey"	"transacoes"	"usuario_id"	"usuarios"	"id"
"webhook_events_transacao_id_fkey"	"webhook_events"	"transacao_id"	"transacoes"	"id"
"capitulo_keyword_images_capitulo_id_fkey"	"capitulo_keyword_images"	"capitulo_id"	"capitulos"	"id"
"resumo_audio_resumo_id_fkey"	"resumo_audio"	"resumo_id"	"resumos"	"id"
"learning_paths_categoria_id_fkey"	"learning_paths"	"categoria_id"	"categorias"	"id"
"learning_path_items_path_id_fkey"	"learning_path_items"	"caminho_id"	"learning_paths"	"id"
"user_learning_paths_path_id_fkey"	"user_learning_paths"	"caminho_id"	"learning_paths"	"id"
"user_learning_paths_usuario_id_fkey"	"user_learning_paths"	"usuario_id"	"usuarios"	"id"
"usuario_goals_usuario_id_fkey"	"usuario_meta"	"usuario_id"	"usuarios"	"id"
"capitulo_examples_capitulo_id_fkey"	"capitulo_examples"	"capitulo_id"	"capitulos"	"id"
"chapter_images_capitulo_id_fkey"	"chapter_images"	"capitulo_id"	"capitulos"	"id"
"topico_resumos_resumo_id_fkey"	"topico_resumos"	"resumo_id"	"resumos"	"id"
"topico_resumos_topico_id_fkey"	"topico_resumos"	"topico_id"	"topicos"	"top_id"
"topico_capitulos_capitulo_id_fkey"	"topico_capitulos"	"capitulo_id"	"capitulos"	"id"
"topico_capitulos_topico_id_fkey"	"topico_capitulos"	"topico_id"	"topicos"	"top_id"
"usuario_preferences_usuario_id_fkey"	"usuario_preferences"	"usuario_id"	"usuarios"	"id"
"events_usuario_id_fkey"	"events"	"usuario_id"	"usuarios"	"id"
"topico_compilados_topico_id_fkey"	"topico_compilados"	"topico_id"	"topicos"	"top_id"
"subuser_links_owner_usuario_id_fkey"	"subuser_links"	"owner_id"	"usuarios"	"id"
"subuser_links_sub_usuario_id_fkey"	"subuser_links"	"subuser_id"	"usuarios"	"id"
"subuser_categorias_categoria_id_fkey"	"subuser_categorias"	"categoria_id"	"categorias"	"id"
"subuser_categorias_subuser_link_id_fkey"	"subuser_categorias"	"subuser_link_id"	"subuser_links"	"id"
"subuser_trilhas_learning_path_id_fkey"	"subuser_trilhas"	"learning_path_id"	"learning_paths"	"id"
"subuser_trilhas_subuser_link_id_fkey"	"subuser_trilhas"	"subuser_link_id"	"subuser_links"	"id"
"subuser_topicos_subuser_link_id_fkey"	"subuser_topicos"	"subuser_link_id"	"subuser_links"	"id"
"subuser_topicos_topico_id_fkey"	"subuser_topicos"	"topico_id"	"topicos"	"top_id"
"fk_news_seen_news"	"news_seen"	"news_id"	"news_items"	"id"
"fk_news_seen_user"	"news_seen"	"user_id"	"usuarios"	"id"
"checkpoints_capitulo_id_fkey"	"checkpoints"	"capitulo_id"	"capitulos"	"id"
"checkpoints_livro_id_fkey"	"checkpoints"	"livro_id"	"livros"	"id"
"checkpoints_rubric_id_fkey"	"checkpoints"	"rubric_id"	"rubrics"	"id"
"challenges_checkpoint_id_fkey"	"challenges"	"checkpoint_id"	"checkpoints"	"id"
"challenges_rubric_id_fkey"	"challenges"	"rubric_id"	"rubrics"	"id"
"user_progress_checkpoint_id_fkey"	"user_progress"	"checkpoint_id"	"checkpoints"	"id"
"user_progress_usuario_id_fkey"	"user_progress"	"usuario_id"	"usuarios"	"id"
"task_submissions_challenge_id_fkey"	"task_submissions"	"challenge_id"	"challenges"	"id"
"task_submissions_usuario_id_fkey"	"task_submissions"	"usuario_id"	"usuarios"	"id"
"user_badges_badge_id_fkey"	"user_badges"	"badge_id"	"badges"	"id"
"user_badges_usuario_id_fkey"	"user_badges"	"usuario_id"	"usuarios"	"id"
"user_xp_usuario_id_fkey"	"user_xp"	"usuario_id"	"usuarios"	"id"
"minigame_definitions_challenge_id_fkey"	"minigame_definitions"	"challenge_id"	"challenges"	"id"
"minigame_definitions_checkpoint_id_fkey"	"minigame_definitions"	"checkpoint_id"	"checkpoints"	"id"
"minigame_custom_themes_created_by_user_id_fkey"	"minigame_custom_themes"	"created_by_user_id"	"usuarios"	"id"
"minigame_custom_questions_created_by_user_id_fkey"	"minigame_custom_questions"	"created_by_user_id"	"usuarios"	"id"
"minigame_custom_questions_tema_id_fkey"	"minigame_custom_questions"	"tema_id"	"minigame_custom_themes"	"id"
"plan_settings_assinatura_id_fkey"	"plan_settings"	"assinatura_id"	"assinatura"	"id"
"faqs_author_user_id_fkey"	"faqs"	"author_user_id"	"usuarios"	"id"
"support_threads_user_id_fkey"	"support_threads"	"user_id"	"usuarios"	"id"
"support_messages_sender_user_id_fkey"	"support_messages"	"sender_user_id"	"usuarios"	"id"
"support_messages_thread_id_fkey"	"support_messages"	"thread_id"	"support_threads"	"id"
"classrooms_owner_usuario_id_fkey"	"classrooms"	"owner_usuario_id"	"usuarios"	"id"
"subclass_link_fkey"	"subuser_classrooms"	"subuser_link_id"	"subuser_links"	"id"
"subclass_classroom_fkey"	"subuser_classrooms"	"classroom_id"	"classrooms"	"id"
"subshare_link_fkey"	"subuser_shares"	"subuser_link_id"	"subuser_links"	"id"
"subshare_from_owner_fkey"	"subuser_shares"	"from_owner_id"	"usuarios"	"id"
"subshare_to_owner_fkey"	"subuser_shares"	"to_owner_id"	"usuarios"	"id"
"subsim_link_fkey"	"subuser_simulados"	"subuser_link_id"	"subuser_links"	"id"
"subsim_simulado_fkey"	"subuser_simulados"	"simulado_id"	"simulados"	"id"
"subliv_link_fkey"	"subuser_livros"	"subuser_link_id"	"subuser_links"	"id"
"subliv_livro_fkey"	"subuser_livros"	"livro_id"	"livros"	"id"
"submgt_link_fkey"	"subuser_minigame_themes"	"subuser_link_id"	"subuser_links"	"id"
"submgt_tema_fkey"	"subuser_minigame_themes"	"tema_id"	"minigame_custom_themes"	"id"
"public"	"classroom_shares"	"id"	"integer"
"public"	"classroom_shares"	"classroom_id"	"integer"
"public"	"classroom_shares"	"from_owner_id"	"integer"
"public"	"classroom_shares"	"to_owner_id"	"integer"
"public"	"classroom_shares"	"created_at"	"timestamp with time zone"
"cls_share_classroom_fkey"	"classroom_shares"	"classroom_id"	"classrooms"	"id"
"cls_share_from_owner_fkey"	"classroom_shares"	"from_owner_id"	"usuarios"	"id"
"cls_share_to_owner_fkey"	"classroom_shares"	"to_owner_id"	"usuarios"	"id"